Aoraki.Web/Controllers/JournalController.cs
using System;
using System.Threading.Tasks;
using Aoraki.Web.Contracts;
using Aoraki.Web.Extensions;
using Aoraki.Web.Models;
using Aoraki.Web.Models.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace Aoraki.Web.Controllers
{
    public class JournalController : Controller
    {
        private const int PostsPerPage = 10;

        private readonly IJournalPostService _postService;

        public JournalController(IJournalPostService postService)
        {
            _postService = postService;
        }

        [ResponseCache(Duration = 14400, VaryByQueryKeys = new[] { "page" })]
        public async Task<IActionResult> Index(int page = 1)
        {
            var totalPosts = await _postService.GetTotalPostCountAsync();
            var totalPages = (int)Math.Ceiling((decimal)totalPosts / (decimal)PostsPerPage);

            if (page < 1)
                return RedirectToAction(nameof(Index), new { page = 1 });
            if (page > totalPages)
                return RedirectToAction(nameof(Index), new { page = totalPages });

            var posts = await _postService.GetPostsAsync((page - 1) * PostsPerPage, PostsPerPage);
            return View(new JournalIndexViewModel
            {
                Pagination = new Pagination { CurrentPage = page, TotalPages = totalPages },
                Posts = posts
            });
        }

        [ResponseCache(Duration = 14400)]
        public async Task<IActionResult> Archive()
        {
            return View(await _postService.GetPostsArchiveAsync());
        }

        [ResponseCache(Duration = 604800)]
        public async Task<IActionResult> Read(int year, string slug)
        {
            var post = await _postService.GetPostBySlugAsync(slug);
            if (post == null) return NotFound();
            if (post.Published?.Year != year) return new NotFoundResult();
            return View(post);
        }

        [Produces("text/plain")]
        [ResponseCache(Duration = 604800)]
        [Route("journal/{year}/{slug}.txt")]
        public async Task<IActionResult> ReadPlaintext(string slug)
        {
            var post = await _postService.GetPostBySlugAsync(slug);
            if (post == null) return NotFound();
            return Ok(post.ToPlainText());
        }

        [Produces("text/plain")]
        [ResponseCache(Duration = 604800)]
        [Route("journal/{year}/{slug}.md")]
        public async Task<IActionResult> ReadMarkdown(string slug)
        {
            var post = await _postService.GetPostBySlugAsync(slug);
            if (post == null) return NotFound();
            return Ok(post.Content);
        }

        [Produces("application/json")]
        [ResponseCache(Duration = 604800)]
        [Route("journal/{year}/{slug}.json")]
        public async Task<IActionResult> ReadJson(string slug)
        {
            var post = await _postService.GetPostBySlugAsync(slug);
            if (post == null) return NotFound();
            return Ok(post);
        }
    }
}

Aoraki.Web/Views/Shared/PanelbearTag.cshtml
<!-- Panelbear Analytics - We respect your privacy -->
<script async src="https://cdn.panelbear.com/analytics.js?site=914xZoJ9Foh"></script>
<script>
    window.panelbear = window.panelbear || function(){ window.panelbearQ = window.panelbearQ || []; panelbearQ.push(arguments); };
    panelbear('config', { site: '914xZoJ9Foh' });
</script>

Aoraki.Web/Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="en" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="referrer" content="no-referrer-when-downgrade">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="HandheldFriendly" content="True">

    <title>@ViewData["Title"] - matts blog</title>

    @await Html.PartialAsync("Canonical")

    <style type="text/css">
        html,
        body {
            font-size: 14px;
            font-family: sans-serif;
        }

        h1,
        h2,
        h3,
        h4,
        h5,
        h6 {
            font-family: serif;
        }

        hr {
            border: none;
            border-bottom: 1px dashed #c3c3c3;
        }

        .innerwidth {
            max-width: 550px;
            margin: 0 auto;
        }

        .readon {
            display: inline-block;
        }

        .clearfix:after {
            content: "";
            display: table;
            clear: both;
        }

        nav hr {
            border: none;
            border-bottom: 1px solid #c3c3c3;
        }

        main {
            margin: 20px auto !important;
        }

        pre {
            font-family: monospace;
            overflow: auto;
            padding: 10px;
            background: #f2f2f2;
        }

        article.journal .lead {
            margin: 2px 0 0;
        }

        article.journal h1.title {
            margin: 0;
        }

        article.journal .date {
            color: #666;
            font-size: 12px;
        }

        article.journal .bleb {
            margin: 0 0 10px;
        }

        article.journal img {
            margin: 28px auto;
            padding: 4px;
            max-width: calc(100% - 10px);
            display: block;
            border: 1px solid #d5d5d5;
        }

        @@media (prefers-color-scheme: dark) {
            html,
            body {
                background: #000;
                color: #dbdbdb;
            }

            a:not(:active) {
                color: #88f;
            }

            a:visited {
                color: #bc73ff;
            }

            pre {
                background: #373737;
            }

            hr,
            nav hr,
            article.journal img {
                border-color: #444;
            }

            article.journal .date {
                color: #959595;
            }

            article.journal img {
                opacity: .75;
            }

            article.journal img:hover {
                opacity: 1
            }
        }
    </style>
    @await RenderSectionAsync("Styles", required: false)
    @await Html.PartialAsync("PanelbearTag")
</head>

<body>
    <nav>
        <div class="innerwidth">
            <b><a asp-controller="Journal" asp-action="Index">matts blog</a></b> /
            <a asp-controller="Journal" asp-action="Archive">archive</a>
        </div>
        <hr />
    </nav>

    <main>
        @RenderBody()
    </main>

    <div class="endmatter">
        <div class="innerwidth">
            <hr />
            <p>&copy; @DateTimeOffset.UtcNow.Year</p>
        </div>
    </div>

    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>